//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesReparacion
    {
        public int NumReparacion { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> Unidades { get; set; }
    
        public virtual Reparaciones Reparaciones { get; set; }
        public virtual Piezas Piezas { get; set; }
    }
}
